name: Install and Check Tippacanoe
on:
  schedule:
    - cron: '0 2 */2 * *' # Runs daily at 2 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tippecanoe
        run: |
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          git checkout tags/2.75.1
          make -j
          sudo make install
          tippecanoe --version