name: Deploy OSConnect Viewer
on:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup file for deployment
              run: |
                mkdir -p osconnect-viewer
                cp data-viewer/tdei-viewer.html osconnect-viewer/index.html
            - name: Deploy OSConnect Viewer to Static Website
              uses: Azure/static-web-apps-deploy@v1
              with:
                azure_static_web_apps_api_token: ${{ secrets.OSCONNECT_VIEWER_AZURE_STATIC_WEB_APPS_API_TOKEN }}
                azure_static_web_apps_name: "osconnect-viewer" # Azure Static Web App name
                action: "upload"
                app_location: "osconnect-viewer" # App source code path
                api_location: "" # Api source code path - optional
                output_location: "" # Built app content directory - optional
                skip_app_build: true